repos:
# Base repo
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Code formatting using Black (python)
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black

# Dockerfile lint
- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]

# Code formatting using beautysh (bash)
- repo: https://github.com/lovesegfault/beautysh
  rev: v6.2.1
  hooks:
    - id: beautysh
