services:
  # Prerequisites: Pull base images before using container-prep
  #   docker pull talinx/jp2a
  container-prep:
    image: ghcr.io/cscfi/hpcs/container-prep:dev-20260330
    command:
      - "--config"
      - "/tmp/hpcs-client.conf"
      - "-b"
      - "talinx/jp2a"
      - "-s"
      - "/tmp"
      - "--sif-host-path"
      - "${PWD}/local_dev"
      - "-e"
      - "-u"
      - "hardwick"
      - "-c"
      - "nid[002275-002276,002500-002501,002504-002506,002595-002597]" #"nid003044"
      - "--data-path"
      - "/tmp/encrypted_prepared_jp2a.sif"
      - "--data-path-at-rest"
      - "/scratch/project_462000906/hardwick/"
      - "--username"
      - "hardwick"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/local_dev:/tmp
      - $PWD/.ssh:/tmp/.ssh
    environment:
      - PWD=${PWD}
      - HOME=${HOME}
    group_add:
      - "145"  # docker group
    network_mode: host

  data-prep:
    image: ghcr.io/cscfi/hpcs/data-prep:dev-20260324
    command:
      - "--config"
      - "/tmp/hpcs-client.conf"
      - "-i"
      - "/tmp/jp2a_input"
      - "-o"
      - "/tmp/"
      - "-u"
      - "hardwick"
      - "-c"
      - "nid[002275-002276,002500-002501,002504-002506,002595-002597]" #"nid003044"
      - "--data-path"
      - "/tmp/encrypted_jp2a_input.tgz"
      - "--data-path-at-rest"
      - "/scratch/project_462000906/hardwick/"
      - "--username"
      - "hardwick"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/local_dev:/tmp
      - $PWD/.ssh:/tmp/.ssh
    environment:
      - PWD=${PWD}
      - HOME=${HOME}
    group_add:
      - "145"  # docker group
    network_mode: host

  job-prep:
    image: ghcr.io/cscfi/hpcs/job-prep:dev-20260325
    command:
      - "--config"
      - "/tmp/hpcs-client.conf"
      - "-N"
      - "1"
      - "-p"
      - "debug"
      - "-t"
      - "00:10:00"
      - "-A"
      - "project_462000906"
      - "--nodelist"
      - "nid[002275-002276,002500-002501,002504-002506,002595-002597]" # "nid003044"
      - "-J"
      - "jp2a_job"
      - "--workdir"
      - "/scratch/project_462000906/hardwick"
      - "-ai"
      - "/scratch/project_462000906/hardwick/encrypted_prepared_jp2a.sif.info.yaml"
      - "-di"
      - "/scratch/project_462000906/hardwick/encrypted_jp2a_input.tgz.info.yaml"
      - "-args"
      - "\"\\\" /sd-container/encrypted/jp2a_input/image.png --width=100 --output=/sd-container/output/result \\\"\""
      - "-i"
      - "/scratch/project_462000906/hardwick/verification_scripts"
      - "-o"
      - "/scratch/project_462000906/hardwick/verification_scripts"
      - "-flags"
      - "--env TERM=xterm-256color"
      - "--follow"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/local_dev:/tmp
      - $PWD/.ssh:/tmp/.ssh
    environment:
      - PWD=${PWD}
      - HOME=${HOME}
    group_add:
      - "145"  # docker group
    network_mode: host
