# Service definition for spire-oidc (expose the OIDC socket)
apiVersion: v1
kind: Service
metadata:
  name: hpcs-server
spec:
  type: {{ .Values.hpcs.service.type }}
  selector:
    app: hpcs-server
  ports:
    - name: https
      port: {{ .Values.hpcs.server.port }}
      targetPort: hpcs-server
      {{- if eq .Values.hpcs.service.type "NodePort" }}
      nodePort: {{ .Values.hpcs.service.port }}
      {{- end -}}
