# Service definition for spire-oidc (expose the OIDC socket)
apiVersion: v1
kind: Service
metadata:
  name: hpcs-server
  namespace: hpcs
spec:
  clusterIP: None
  selector:
    app: hpcs-server
  ports:
    - name: https
      port: 10080
      targetPort: hpcs-server
