apiVersion: v1
kind: ConfigMap
metadata:
  name: hpcs-server
  namespace: hpcs
data:
  hpcs-server.conf: |
    [spire-server]
    address = localhost
    port = 8081
    trust-domain = hpcs
    pre-command = ""
    spire-server-bin = spire-server
    socket-path = /var/run/sockets/server/api.sock

    [spire-agent]
    spire-agent-socket = /run/sockets/agent/agent.sock

    [vault]
    url = http://vault:8200
    server-role = hpcs-server

  agent.conf: |
    agent {
      data_dir = "./data/agent"
      log_level = "DEBUG"
      trust_domain = "hpcs"
      server_address = "spire-server"
      server_port = 8081
      socket_path = "/var/run/sockets/agent/agent.sock"
      admin_socket_path = "/var/run/sockets/admin/admin.sock"

      # Insecure bootstrap is NOT appropriate for production use but is ok for
      # simple testing/evaluation purposes.
      insecure_bootstrap = true
    }

    plugins {
      KeyManager "disk" {
            plugin_data {
                directory = "./data/agent"
            }
        }

      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "docker-desktop"
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
        }
      }

      WorkloadAttestor "unix" {
        plugin_data {
          discover_workload_path = true
        }
      }
    }
