# Service definition for spire-oidc (expose the OIDC socket)
apiVersion: v1
kind: Service
metadata:
  name: spire-oidc
  namespace: hpcs
spec:
  type: LoadBalancer
  selector:
    app: spire-server
  ports:
    - name: https
      port: 443
      targetPort: hpcs-nginx
