apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-oidc
  namespace: hpcs
data:
  oidc-discovery-provider.conf: |
    log_level = "debug"
    domains = ["spire-oidc"]
    listen_socket_path = "/tmp/spire-server/private/oidc-api.sock"

    server_api {
        address = "unix:///tmp/spire-server/private/api.sock"
    }

    health_checks {}
