apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-discovery-provider
  namespace: spire
data:
  oidc-discovery-provider.conf: |
    log_level = "debug"
    domains = ["spire-oidc"]
    listen_socket_path = "/server.sock"

    server_api {
        address = "unix:///tmp/spire-server/private/api.sock"
    }