apiVersion: v1
kind: ConfigMap
metadata:
  name: hpcs-server
data:
  hpcs-server.conf: |
    [spire-server]
    address = {{ .Values.server.spire.address }}
    port = {{ .Values.server.spire.port }}
    trust-domain = {{ .Values.server.spire.trustDomain }}
    pre-command = ""
    spire-server-bin = spire-server
    socket-path = /var/run/sockets/server/api.sock

    [spire-agent]
    spire-agent-socket = /run/sockets/agent/agent.sock

    [vault]
    url = {{ .Values.server.vault.address }}:{{ .Values.server.vault.port }}
    server-role = {{ .Values.server.vault.role }}

  agent.conf: |
    agent {
      data_dir = "./data/agent"
      log_level = "{{ .Values.agent.logLevel }}"
      trust_domain = "{{ .Values.server.spire.trustDomain }}"
      server_address = "{{ .Values.agent.server.address }}"
      server_port = {{ .Values.agent.server.port }}
      socket_path = "/var/run/sockets/agent/agent.sock"
      admin_socket_path = "/var/run/sockets/admin/admin.sock"

      # Insecure bootstrap is NOT appropriate for production use but is ok for
      # simple testing/evaluation purposes.
      insecure_bootstrap = true
    }

    plugins {
      KeyManager "disk" {
            plugin_data {
                directory = "./data/agent"
            }
        }

      NodeAttestor "k8s_psat" {
        plugin_data {
          cluster = "{{ .Values.agent.clusterName }}"
        }
      }

      WorkloadAttestor "k8s" {
        plugin_data {
        }
      }

      WorkloadAttestor "unix" {
        plugin_data {
          discover_workload_path = true
        }
      }
    }
