---
apiVersion: v1
kind: Secret
metadata:
  namespace: hpcs
  name: spire-oidc-certs
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- $.Files.Get "files/spire-oidc.crt" | nindent 4 }}
  tls.key: |
    {{- $.Files.Get "files/spire-oidc.key" | nindent 4 }}
