apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-bundle
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
data:
  server.conf: |
    server {
      bind_address = "{{ .Values.server.bindAddress }}"
      bind_port = "{{ .Values.server.port }}"
      socket_path = "/tmp/spire-server/private/api.sock"
      trust_domain = "{{ .Values.server.trustDomain }}"
      data_dir = "/run/spire/data"
      log_level = "{{ .Values.server.logLevel }}"
      ca_key_type = "{{ .Values.server.caKeyType }}"

      jwt_issuer = "spire-server"
      default_jwt_svid_ttl = "{{ .Values.server.defaultJWTttl }}"

      ca_subject = {
        country = ["US"],
        organization = ["SPIFFE"],
        common_name = "",
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }

      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "{{ .Values.server.clusterName }}" = {
              use_token_review_api_validation = true
              service_account_allow_list = ["hpcs:hpcs-server"]
            }
          }
        }
      }

      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }

      Notifier "k8sbundle" {
        plugin_data {
            namespace = "{{ .Release.Namespace }}"
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "{{ .Values.server.health.bindAddress }}"
      bind_port = "{{ .Values.server.health.port }}"
      live_path = "/live"
      ready_path = "/ready"
    }
