# Service definition for spire server
apiVersion: v1
kind: Service
metadata:
  name: spire-server
spec:
  type: LoadBalancer
  selector:
    app: spire-server
  ports:
    - name: tcp-spire
      port: {{ .Values.server.port }}
      targetPort: spire-server
