apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      shareProcessNamespace: true
      containers:
        - name: hpcs-nginx
          image: nginx
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/
              readOnly: true
            - name: spire-server-socket
              mountPath: /tmp/spire-server/private
              readOnly: false
            - name: nginx-certs
              mountPath: /certs
              readOnly: true
          ports:
            - containerPort: {{ .Values.oidc.port }}
              name: hpcs-nginx
        - name: spire-server
          image: {{ .Values.server.image.repository }}/spire-server:{{ .Values.server.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
            - -config
            - /run/spire/config/server.conf
          ports:
            - containerPort: {{ .Values.server.port }}
              name: spire-server
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
              readOnly: false
            - name: spire-server-socket
              mountPath: /tmp/spire-server/private
              readOnly: false
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.server.health.port }}
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.server.health.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: spire-oidc
          image: {{ .Values.server.image.repository }}/oidc-discovery-provider:{{ .Values.server.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
          - -config
          - /run/spire/oidc/config/oidc-discovery-provider.conf
          volumeMounts:
          - name: spire-server-socket
            mountPath: /tmp/spire-server/private
            readOnly: false
          - name: spire-oidc-config
            mountPath: /run/spire/oidc/config/
            readOnly: true
          - name: spire-data
            mountPath: /run/spire/data
            readOnly: false
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.server.health.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: nginx-config
          configMap:
            name: hpcs-nginx
        - name: spire-config
          configMap:
            name: spire-server
        - name: spire-server-socket
          hostPath:
            path: /run/spire/sockets/server
            type: DirectoryOrCreate
        - name: spire-oidc-config
          configMap:
            name: spire-oidc
        - name: nginx-certs
          hostPath:
            path: /etc/certs/hpcs-spire-oidc
            type: DirectoryOrCreate
  volumeClaimTemplates:
    - metadata:
        name: spire-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.server.storageSize }}
