spire:
  oidc:
    logLevel: debug
    port: 443
    service:
      type: NodePort
      port: 30001
  server:
    image:
      repository: ghcr.io/spiffe
      # tag of the image, defaults to .Chart.AppVersion
      # tag:
      pullPolicy: IfNotPresent

    bindAddress: "0.0.0.0"
    port: 8081
    trustDomain: hpcs
    logLevel: DEBUG
    caKeyType: rsa-4096
    defaultJWTttl: "1h"
    clusterName: hpcs
    health:
      bindAddress: "0.0.0.0"
      port: 8080
    storageSize: "1G"
    service:
      type: NodePort
      port: 30002
hpcs:
  image:
    repository: ghcr.io/cscfi/hpcs
    # tag of the image, defaults to .Chart.AppVersion
    # tag:
    pullPolicy: IfNotPresent
  server:
    port: 10080
    spire:
      address: localhost
      port: 8081
      trustDomain: hpcs
    vault:
      address: http://vault
      port: 8200
      role: hpcs-server
  agent:
    logLevel: DEBUG
    server:
      address: spire-server
      port: 8081
    clusterName: hpcs
  storageSize: "1Gi"
  service:
    type: NodePort
    port: 30003
vaultService:
  present: true
  nodePort: 30004
