apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hpcs-server
  labels:
    app: hpcs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpcs-server
  serviceName: hpcs-server
  template:
    metadata:
      labels:
        app: hpcs-server
    spec:
      serviceAccountName: hpcs-server
      shareProcessNamespace: true
      containers:
        - name: hpcs-server
          image: {{ .Values.image.repository }}/server:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.server.port }}
              name: hpcs-server
          volumeMounts:
            - name: hpcs-server-configs
              mountPath: /tmp/
              readOnly: false
            - name: hpcs-spire-sockets
              mountPath: /var/run/sockets
              readOnly: false
            - name: hpcs-spire-agent-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
      volumes:
        - name: hpcs-server-configs
          configMap:
            name: hpcs-server
        - name: hpcs-spire-sockets
          hostPath:
            path: /run/spire/sockets
            type: DirectoryOrCreate
        - name: hpcs-spire-agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: spire-agent
                  expirationSeconds: 7200
                  audience: spire-server
  volumeClaimTemplates:
    - metadata:
        name: spire-agent-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storageSize }}
