# Service definition for spire-oidc (expose the OIDC socket)
apiVersion: v1
kind: Service
metadata:
  name: hpcs-server
spec:
  clusterIP: None
  selector:
    app: hpcs-server
  ports:
    - name: https
      port: {{ .Values.server.port }}
      targetPort: hpcs-server
